backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
editor:
  preview: false
collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "coverImage",
          widget: "image",
          required: true,
        }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "heroCopy", widget: "text" }
          - label: "Services"
            name: "services"
            widget: list
            fields:
              - { label: "Name", name: "title", widget: "string" }
              - { label: "Description", name: "copy", widget: "text" }
              - { label: "Icon", name: "img", widget: "image" }
              - { label: "Background", name: "background", widget: "image" }
          - label: "Slider"
            name: "slider"
            widget: "list"
            summary: "{{fields.image}}"
            field: { label: Image, name: image, widget: image }
      - label: "Settings"
        name: "settings"
        file: "content/settings.md"
        fields:
          - { label: "Site Name", name: "siteName", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Email 2", name: "email2", widget: "string" }
          - { label: "Phone", name: "phone2", widget: "string" }
          - { label: "Facebook Link", name: "facebook", widget: "string" }
          - { label: "Twitter Link", name: "twitter", widget: "string" }
          - { label: "Linkedin Link", name: "linkedin", widget: "string" }
          - { label: "Instagram Link", name: "instagram", widget: "string" }
          - { label: "Youtube Link", name: "youtube", widget: "string" }
      - label: "Locations"
        name: "locations"
        file: "content/locations.md"
        fields:
          - label: "Top Locations"
            name: "locations"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "img", widget: "image" }
          - label: "All Locations"
            name: "allLocations"
            widget: "list"
            add_to_top: true
      - label: "SEO"
        name: "seo"
        file: "content/seo.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Site URL", name: "siteUrl", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Keywords"
            name: "keywords"
            widget: "list"
            add_to_top: true
      - label: "Testimonials"
        name: "testimonials"
        file: "content/testimonials.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            add_to_top: true
            summary: "{{fields.quote}} - {{fields.name}}"
            fields:
              - { label: Quote, name: quote, widget: string }
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
      - label: "Contact Us"
        name: "contact-us"
        file: "content/contact-us.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Text", name: "copy", widget: "text" }
      - label: "About Us"
        name: "about-us"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - { label: "Text", name: "copy", widget: "text" }
          - { label: "Team Intro", name: "teamIntro", widget: "text" }
          - label: "Team"
            name: "team"
            widget: "list"
            add_to_top: true
            summary: "{{fields.name}} - {{fields.title}}"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Image, name: img, widget: image }
              - { label: Bio, name: bio, widget: text }
